# ----------------------------------------------------------------------------
# Copyright (C) 2021 Deepchecks (https://www.deepchecks.com)
#
# This file is part of Deepchecks.
# Deepchecks is distributed under the terms of the GNU Affero General
# Public License (version 3 or later).
# You should have received a copy of the GNU Affero General Public License
# along with Deepchecks.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------
#
name: Notebooks Generation

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
  

jobs:
  regenerate-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Regenerate Notebooks
        run: make regenerate-examples
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          add-paths: |
            examples/*
          token: ${{ secrets.CI_GH_TOKEN }}
          commit-message: '[Automatic] Examples Update'
          delete-branch: true
          branch: examples-update
          title: '[Automatic PR] Notebooks Updates'
          labels: |
            chore/ci
          draft: false
